import type { Config } from "tailwindcss";

// Precision Archival design system tokens — canonical source: .design/DESIGN.md
// (NOT the .design/*.html mockups' embedded Tailwind config, which is outdated per 01-UI-SPEC.md)
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        background: "#fff8f6",
        surface: "#fff8f6",
        "surface-dim": "#efd4d0",
        "surface-bright": "#fff8f6",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#fff0ee",
        "surface-container": "#ffe9e6",
        "surface-container-high": "#fee2dd",
        "surface-container-highest": "#f8dcd8",
        "on-surface": "#261816",
        "on-surface-variant": "#5a403c",
        "inverse-surface": "#3d2c2a",
        "inverse-on-surface": "#ffedea",
        outline: "#8e706b",
        "outline-variant": "#e3beb8",
        "surface-tint": "#b52619",
        primary: "#610000",
        "on-primary": "#ffffff",
        "primary-container": "#8b0000",
        "on-primary-container": "#ff907f",
        "inverse-primary": "#ffb4a8",
        secondary: "#5e5e5e",
        "on-secondary": "#ffffff",
        "secondary-container": "#e2e2e2",
        "on-secondary-container": "#646464",
        tertiary: "#2b2c2c",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#424242",
        "on-tertiary-container": "#afaeae",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#ffdad4",
        "primary-fixed-dim": "#ffb4a8",
        "on-primary-fixed": "#410000",
        "on-primary-fixed-variant": "#920703",
        "secondary-fixed": "#e2e2e2",
        "secondary-fixed-dim": "#c6c6c6",
        "on-secondary-fixed": "#1b1b1b",
        "on-secondary-fixed-variant": "#474747",
        "tertiary-fixed": "#e3e2e2",
        "tertiary-fixed-dim": "#c7c6c6",
        "on-tertiary-fixed": "#1b1c1c",
        "on-tertiary-fixed-variant": "#464747",
        "on-background": "#261816",
        "surface-variant": "#f8dcd8",
      },
      fontFamily: {
        headings: ["'Hanken Grotesk'", "sans-serif"],
        body: ["Inter", "sans-serif"],
        mono: ["'JetBrains Mono'", "monospace"],
      },
      fontSize: {
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "headline-xl": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "code-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
      },
      spacing: {
        base: "4px",
        xs: "8px",
        sm: "12px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        "2xl": "48px",
        "3xl": "64px",
        "panel-width-side": "280px",
        "panel-width-tools": "320px",
        gutter: "1px",
      },
      borderRadius: {
        sm: "0.125rem",
        DEFAULT: "0.25rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
} satisfies Config;
