import type { DocumentIssuanceDetail } from "../../lib/documentIssuances";

const STATUS_LABELS: Record<string, string> = {
  success: "Success",
  failure: "Failure",
};

function formatDate(value: string) {
  return new Date(value).toLocaleString();
}

interface IssuancePropertiesProps {
  detail: DocumentIssuanceDetail;
}

export default function IssuanceProperties({ detail }: IssuancePropertiesProps) {
  return (
    <section>
      <h2 className="mb-sm font-headings text-[18px] font-bold text-on-surface">
        Issuance Properties
      </h2>
      <div className="rounded border border-outline-variant bg-surface-container-lowest p-md text-sm text-on-surface">
        <dl className="divide-y divide-outline-variant/40">
          <div className="flex justify-between py-xs gap-md">
            <dt className="text-on-surface-variant break-all select-all">Issuance Status</dt>
            <dd className="font-bold text-right break-all select-all">
              {STATUS_LABELS[detail.status] || detail.status}
            </dd>
          </div>
          <div className="flex justify-between py-xs gap-md">
            <dt className="text-on-surface-variant break-all select-all">Design Version</dt>
            <dd className="font-bold text-right break-all select-all">
              {detail.design_version_number ?? "None"} · {detail.design_status}
            </dd>
          </div>
          <div className="flex justify-between py-xs gap-md">
            <dt className="text-on-surface-variant break-all select-all">Generated By</dt>
            <dd className="font-bold text-right break-all select-all">
              {detail.generated_by_email}
            </dd>
          </div>
          <div className="flex justify-between py-xs gap-md">
            <dt className="text-on-surface-variant break-all select-all">Created At</dt>
            <dd className="font-bold text-right break-all select-all">
              {formatDate(detail.created_at)}
            </dd>
          </div>
          <div className="flex flex-col py-xs gap-xs">
            <dt className="text-on-surface-variant">Issuance ID</dt>
            <dd className="font-mono text-body-sm break-all select-all text-on-surface">
              {detail.id}
            </dd>
          </div>
        </dl>
      </div>
    </section>
  );
}
