import time

from fastapi.testclient import TestClient

from app.auth.session import decrypt_session, encrypt_session
from app.config import settings


def test_proxy_unauthenticated_request(
    client: tuple[TestClient, callable, list],
) -> None:
    test_client, add_handler, requests_received = client

    # Mock backend response
    add_handler(
        method="GET",
        url_part="api/document-designs",
        status_code=200,
        json_data={"data": []},
    )

    response = test_client.get("/api/document-designs")
    assert response.status_code == 200
    assert response.json() == {"data": []}

    # Verify requests sent to backend
    assert len(requests_received) == 1
    backend_req = requests_received[0]
    assert "authorization" not in backend_req.headers
    assert "cookie" not in backend_req.headers
    # Host header is generated by httpx to match target backend host, not the original testserver host
    assert backend_req.headers.get("host") != "testserver.local"


def test_proxy_unauthenticated_request_with_bearer_forward(
    client: tuple[TestClient, callable, list],
) -> None:
    test_client, add_handler, requests_received = client

    # Mock backend response
    add_handler(
        method="GET",
        url_part="api/document-designs",
        status_code=200,
        json_data={"data": []},
    )

    response = test_client.get(
        "/api/document-designs",
        headers={"Authorization": "Bearer external-caller-token"},
    )
    assert response.status_code == 200

    assert len(requests_received) == 1
    backend_req = requests_received[0]
    assert backend_req.headers["authorization"] == "Bearer external-caller-token"


def test_proxy_authenticated_request_valid_token(
    client: tuple[TestClient, callable, list], mint_jwt: callable
) -> None:
    test_client, add_handler, requests_received = client

    # Mint a valid token
    access_token = mint_jwt(
        {
            "sub": "user-123",
            "email": "alice@example.com",
            "exp": int(time.time()) + 3600,
        }
    )
    session_cookie = encrypt_session(
        {"access_token": access_token, "refresh_token": "refresh-123"},
        settings.session_secret,
    )
    test_client.cookies.set(
        settings.session_cookie_name, session_cookie, domain="testserver.local"
    )

    # Mock backend response
    add_handler(
        method="POST",
        url_part="api/document-designs",
        status_code=201,
        json_data={"id": "design-1"},
    )

    response = test_client.post("/api/document-designs", json={"name": "New Design"})
    assert response.status_code == 201
    assert response.json() == {"id": "design-1"}

    assert len(requests_received) == 1
    backend_req = requests_received[0]
    assert backend_req.headers["authorization"] == f"Bearer {access_token}"
    assert "cookie" not in backend_req.headers


def test_proxy_authenticated_request_silent_refresh(
    client: tuple[TestClient, callable, list], mint_jwt: callable
) -> None:
    test_client, add_handler, requests_received = client

    # Mint an expired token
    expired_access_token = mint_jwt(
        {
            "sub": "user-123",
            "email": "alice@example.com",
            "exp": int(time.time()) - 3600,
        }
    )
    session_cookie = encrypt_session(
        {"access_token": expired_access_token, "refresh_token": "refresh-123"},
        settings.session_secret,
    )
    test_client.cookies.set(
        settings.session_cookie_name, session_cookie, domain="testserver.local"
    )

    # Mint a new access token that Keycloak will return
    new_access_token = mint_jwt(
        {
            "sub": "user-123",
            "email": "alice@example.com",
            "exp": int(time.time()) + 3600,
        }
    )

    # Mock Keycloak token refresh
    add_handler(
        method="POST",
        url_part="protocol/openid-connect/token",
        status_code=200,
        json_data={
            "access_token": new_access_token,
            "refresh_token": "new-refresh-123",
        },
    )

    # Mock backend response
    add_handler(
        method="GET",
        url_part="api/document-designs",
        status_code=200,
        json_data={"data": ["refreshed"]},
    )

    response = test_client.get("/api/document-designs")
    assert response.status_code == 200
    assert response.json() == {"data": ["refreshed"]}

    # Verify both Keycloak and backend requests were made
    assert len(requests_received) == 2
    kc_req = requests_received[0]
    backend_req = requests_received[1]

    # Verify Keycloak request params
    assert "openid-connect/token" in str(kc_req.url)
    # Verify backend request got the NEW token
    assert backend_req.headers["authorization"] == f"Bearer {new_access_token}"

    # Verify session cookie was updated
    new_cookie_val = test_client.cookies.get(settings.session_cookie_name)
    assert new_cookie_val is not None
    decrypted = decrypt_session(new_cookie_val, settings.session_secret)
    assert decrypted["access_token"] == new_access_token
    assert decrypted["refresh_token"] == "new-refresh-123"


def test_proxy_refresh_failure_clears_cookie(
    client: tuple[TestClient, callable, list], mint_jwt: callable
) -> None:
    test_client, add_handler, requests_received = client

    # Mint expired token
    expired_access_token = mint_jwt(
        {
            "sub": "user-123",
            "email": "alice@example.com",
            "exp": int(time.time()) - 3600,
        }
    )
    session_cookie = encrypt_session(
        {"access_token": expired_access_token, "refresh_token": "refresh-123"},
        settings.session_secret,
    )
    test_client.cookies.set(
        settings.session_cookie_name, session_cookie, domain="testserver.local"
    )

    # Mock Keycloak token refresh failure
    add_handler(
        method="POST",
        url_part="protocol/openid-connect/token",
        status_code=400,
        json_data={"error": "invalid_grant"},
    )

    response = test_client.get("/api/document-designs")
    assert response.status_code == 401
    assert response.json()["reason"] == "token_refresh_failed"

    # Verify session cookie was deleted
    assert test_client.cookies.get(settings.session_cookie_name) in (None, "")
